### ISSUE TITLE
아이템 25. 톱레벨 클래스는 한 파일에 하나만 담으라

### ISSUE THREAD

**Issue by joyerimi** [psychology50/effective-java-study#11]

**Comment by AHNDOIL** [comment]
중복된 톱 클래스가 여러 개일 때 명령어로 컴파일 하지 않고 그냥 idle에서 run을 누르면 어떻게 동작하나요?

**Comment by joyerimi** [comment]
idle에서 실행할 경우, 해당 프로젝트의 전체 파일을 컴파일하기 떄문에 중복된 클래스가 있음을 알 수 있습니다. 따라서, 클래스 중복 에러를 발생시킵니다.
