### ISSUE TITLE
아이템 26. 로 타입은 사용하지 말라

### ISSUE THREAD

**Issue by AHNDOIL** [psychology50/effective-java-study#12]

**Comment by joyerimi** [comment]
Set<?>를 매개변수로 받는 메소드에서 해당 Set을 추가하는 것이 불가능한데, 삭제나 수정은 가능한가요?

**Comment by psychology50** [comment]
instanceof 연산자가 어느 단계에서 객체의 타입을 체크하나요??

**Comment by joyerimi** [comment]
instanceof 연산자로 제네릭 타입 정보를 체크할 수 없는 이유가 뭔가요?

**Comment by AHNDOIL** [comment]
> Set<?>를 매개변수로 받는 메소드에서 해당 Set을 추가하는 것이 불가능한데, 삭제나 수정은 가능한가요?

Set\<?\>에서 값을 삭제하거나 수정하기는 불가능합니다. 만약 정 값을 바꾸고 싶다면 Set\<?\> 을 Set\<Integer\> 와 같이 다른 타입으로 형 변환을 한 후에 값을 수정하는 방법은 있지만 그렇게 되면 타입 불안정하니 의미가 없어져 버립니다. 간단하게 Set<?> 읽기 전용 자료구조로 생각하면 좋을 것 같네요.

**Comment by AHNDOIL** [comment]
> instanceof 연산자가 어느 단계에서 객체의 타입을 체크하나요??

instanceof는 런타임에 객체의 타입을 체크합니다.

```java
if (o instanceof Set){
   Set<?> s = (Set<?>) o;
   //...
}
```

따라서 런타임에 제네릭 타입 정보가 지워지므로,
해당 예제처럼 코드를 작성할 때 비한정적 와일드 카드 타입을 사용해 코드를 지저분하게 만드는 것 보다는 로 타입을 사용해 깔끔하게 하는 것이 좋을 것 같네요.

**Comment by AHNDOIL** [comment]
> instanceof 연산자로 제네릭 타입 정보를 체크할 수 없는 이유가 뭔가요?

앞서 말씀드린 대로 instanceof는 런타임 환경에서 객체의 타입을 체크하기 때문에 컴파일 시에만 알 수 있는 제네릭 타입 정보는 체크할 수 없습니다.
