### ISSUE TITLE
아이템 28. 배열보다는 리스트를 사용하라

### ISSUE THREAD

**Issue by joyerimi** [psychology50/effective-java-study#14]

**Comment by AHNDOIL** [comment]
```java
public class Chooser {
  private final Object[] choiceArray;

  public Chooser(Collection choices) {// 로타입
    choiceArray = choices.toArray();
  }

  public Object choose() {
    Random rnd = ThreadLocalRandom.current();
    return choiceArray[rnd.nextInt(choiceArray.length)];// 형변환 오류 발생 가능
  }
}
```

choiceArray의 타입이 Object[] 배열이기 때문에 Chooser 생성자에서 toArray()를 사용하면 Object 배열이 반환되나요?

**Comment by joyerimi** [comment]
**Chooser** 생성자에서 **toArray()** 메소드를 사용하면 **choiceArray**의 타입은 **Object[]** 배열이 됩니다. 그 이유는 **toArray()** 메소드의 반환 타입이 **Object[]**이기 때문입니다. 


```
Object[] toArray();
```


해당 코드에서 주의해야 할 점은 **Collection**에 저장된 요소의 실제 타입이 **Object**가 아니라 다른 타입인 경우, 배열에 저장된 요소를 가져올 때 형 변환 오류가 발생할 수 있습니다. **Chooser** 클래스의 **choose()** 메소드에서 랜덤하게 요소를 선택할 때 **choiceArray**의 타입은 **Object[]**이기 때문에 요소를 가져올 때 형 변환 오류가 발생할 수 있습니다. 타입 안정성을 보장하기 위해서는 **Collection**의 제네릭 타입을 명시하는 것이 좋습니다.
