### ISSUE TITLE
아이템 31. 한정적 와일드카드를 사용해 API 유연성을 높이라

### ISSUE THREAD

**Issue by AHNDOIL** [psychology50/effective-java-study#17]

**Comment by psychology50** [comment]
- 공변성
- 반공변성
- 불공변성
차이가 무엇인가요?

**Comment by psychology50** [comment]
생산자이자 소비자인 경우는 PECS 원칙을 어떻게 적용할 수 있나요?

**Comment by joyerimi** [comment]
Comparator<E>보다는 Comparator<? super E>를 사용하는 것이 좋은 이유가 뭔가요?

**Comment by psychology50** [comment]
한정적 매개변수와 한정적 와일드카드는 제네릭 프로그래밍에서 사용되는 용어로, 타입 매개변수에 제한을 주는 방법을 나타냅니다. 그러나 두 용어는 다음과 같은 차이점이 있습니다:

1. 한정적 매개변수 (Bounded Type Parameters):
   - 한정적 매개변수는 타입 매개변수에 특정 제약 조건을 부여하는 것을 의미합니다.
   - 한정적 매개변수는 `extends` 키워드를 사용하여 특정 클래스 또는 인터페이스를 상속하거나 구현하는 타입으로 제한됩니다.
   - 한정적 매개변수를 사용하면 특정 타입의 하위 타입만 사용할 수 있으므로, 해당 타입의 멤버에 접근할 수 있습니다.
   - 예를 들어, `<T extends Number>`는 타입 매개변수 `T`를 Number 클래스 또는 Number의 하위 클래스로 제한합니다.

2. 한정적 와일드카드 (Bounded Wildcards):
   - 한정적 와일드카드는 메소드의 매개변수, 제네릭 클래스의 필드 또는 제네릭 타입을 사용하는 다른 상황에서 타입 제한을 설정하는 것을 의미합니다.
   - 한정적 와일드카드는 `?`와 함께 사용되며, `extends` 또는 `super` 키워드를 사용하여 상한 또는 하한을 설정합니다.
   - `? extends Type` 형식은 Type 또는 Type의 하위 타입을 받을 수 있습니다. 즉, 읽기 전용 작업을 수행할 수 있습니다.
   - `? super Type` 형식은 Type 또는 Type의 상위 타입을 받을 수 있습니다. 즉, 쓰기 작업을 수행할 수 있습니다.
   - 예를 들어, `List<? extends Number>`는 Number 클래스 또는 Number의 하위 클래스로 제한된 리스트를 나타냅니다.

요약하자면, 한정적 매개변수는 타입 매개변수에 대한 제약을 설정하는 것이고, 한정적 와일드카드는 메소드나 클래스의 매개변수, 필드 등에 대한 타입 제한을 설정하는 것입니다. 한정적 매개변수는 타입을 사용하는 클래스 또는 인터페이스에서 선언되며, 한정적 와일드카드는 제네릭 타입을 사용하는 다양한 상황에서 유연한 타입 제한을 가능하게 합니다.

**Comment by AHNDOIL** [comment]
> * 공변성
> * 반공변성
> * 불공변성
>   차이가 무엇인가요?

공변성 : 타입 관계에서 상속 관계에 따라 타입 인자가 대입될 수 있는 성질입니다.
대표적으로 배열이 공변성을 가지는데 예를 들어, String은 Object의 하위 타입이라면  String[]도 Object[]의 하위 타입입니다.

반공변성 : 타입 관계에서 상속 관계에 따라 타입 인자의 역순이 대입될 수 있는 성질입니다.
예를 들어 Super가 Sub의 상위 타입이라면 List<Super>는 List<Sub>의 하위 타입입니다.

불공변성 : 타입 관계에서 상속 관계와 관계없이 타입 인자가 대입될 수 없는 성질입니다.
대표적으로 제네릭 타입이 불공변성을 가지는데 예를 들어, String은 Object의 하위 타입이지만 List<String>과 List<Object>는 서로 관계가 없고 별개의 타입으로 취급됩니다.

**Comment by AHNDOIL** [comment]
> 생산자이자 소비자인 경우는 PECS 원칙을 어떻게 적용할 수 있나요?

PECS 원칙은 생산자와 소비자 역할을 분리하여 타입 안전성을 보장하는데 초첨을 맞추고 있으므로 생산자와 소비자의 역할을 동시에 수행하는 경우에는 제네릭 타입을 명확하게 지정해야 합니다.
따라서 와일드카드를 사용하지 않고 명시적으로 제네릭 타입을 지정해야 합니다.

**Comment by AHNDOIL** [comment]
> Comparator보다는 Comparator<? super E>를 사용하는 것이 좋은 이유가 뭔가요?

그렇게 되면 Comparator의 정의 범위를 확장할 수 있어 E의 상위 타입에 대해서도 Comparator를 사용할 수 있으므로 코드의 유연성이 증가합니다. 
예를 들어, E가 Integer 일 경우에 Comparator는 Integer 타입 또는 Integer의 상위 타입인 Number 와 같은 타입을 비교하는데도 사용할 수 있습니다.
