### ISSUE TITLE
아이템 32. 제네릭과 가변인수를 함께 쓸 때는 신중하라

### ISSUE THREAD

**Issue by joyerimi** [psychology50/effective-java-study#18]

**Comment by psychology50** [comment]
${형준님}을 자바죠

**Comment by psychology50** [comment]
```java
static void dangerous(List<String>... stringLists){ // 가변인수 메소드
	List<Integer> intList = List.of(42); // (1)
	Object[] objects = stringLists; // (2)
	objects[0] = intList; // (3) 힙 오염 발생
	String s = stringLists[0].get(0); // (4) ClassCastException
}
```
stringLists[0].get(0)에서 런타임 에러가 발생하나요? 아니면 String으로 형변환하는 과정에서 발생하나요?

**Comment by AHNDOIL** [comment]
```java
 static void dangerous(List<String>... stringLists) {
        List<Integer> intList = List.of(42);
        Object[] objects = stringLists;
        objects[0] = intList; // 힙 오염 발생
        String s = stringLists[0].get(0); // ClassCastException
        //System.out.println(stringLists[0].get(0));
    }
```
해당 코드에서 코드별로 발생하는 컴파일 경고 또는 런타임 에러의 이유에 대해서 설명해주세요

**Comment by joyerimi** [comment]
```java
static void dangerous(List<String>... stringLists){ // 가변인수 메소드
	List<Integer> intList = List.of(42); // (1)
	Object[] objects = stringLists; // (2)
	objects[0] = intList; // (3) 힙 오염 발생
	String s = stringLists[0].get(0); // (4) ClassCastException
}
```

Q1. stringLists[0].get(0)에서 런타임 에러가 발생하나요? 아니면 String으로 형변환하는 과정에서 발생하나요?
A1. stringLists[0].get(0)에서 런타임 에러인 ClassCastException이 발생합니다. 이는 컴파일 타임에는 검증되지 않고 런타임에 stringLists[0].get(0)이 Integer 객체임을 발견할 때 발생합니다.

Q2. 해당 코드에서 코드별로 발생하는 컴파일 경고 또는 런타임 에러의 이유에 대해서 설명해주세요.
A2. (1) Integert 타입의 요소 하나를 갖는 리스트를 생성합니다. (2) 가변인수 매개변수 stringLists를 Object 배열인 objects에 할당합니다. 배열은 공변성을 가지므로 Object[]에 List<String>[]을 대입하는 것이 가능합니다. 이때 타입 안정성이 깨져 컴파일 경고가 발생합니다. (3) object[0]에 intList를 대입합니다. 컴파일 시에는 에러나 경고가 발생하지 않습니다. 그러나 stringList에는 List<String> 타입이어야 할 곳에 List<Integer>가 들어가게 되어 힙 오염이 발생합니다. (4) List<Integer>의 첫 번째 요소를 String으로 받아오려고 하지만, 실제로는 Integer 타입이기 때문에 런타임 에러인 ClassCastException이 발생합니다.
