### ISSUE TITLE
아이템 7. 다 쓴 객체 참조를 해제하라.

### ISSUE THREAD

**Issue by joyerimi** [psychology50/effective-java-study#2]

**Comment by psychology50** [comment]
Garbage Collector가 뭔가요?

**Comment by joyerimi** [comment]
> Garbage Collector가 뭔가요?

간단하게 말하자면 가비지 컬렉터는 자바에서 객체를 해제 시켜주는 역할을 합니다.

**Comment by psychology50** [comment]
약한 참조는 객체의 참조가 사라지면 GC의 대상이 되어 메모리가 회수된다고 말씀하셨는데, 강한 참조도 마찬가지 아닌가요? 정확히 약한 참조를 사용하는 이유에 대해 궁금합니다. ㅎㅎㅎㅎㅎ

**Comment by AHNDOIL** [comment]
캐시 엔트리의 가치를 떨어뜨린다는 의미가 정확히 무엇인가요?

**Comment by AHNDOIL** [comment]
콜백 함수를 약한 참조로 저장하는 방법은 뭔가요?
