### ISSUE TITLE
아이템 34. int 상수 대신 열거 타입을 사용하라

### ISSUE THREAD

**Issue by joyerimi** [psychology50/effective-java-study#20]

**Comment by psychology50** [comment]
열거 타입 생성자에서는 자기 자신을 맵에 추가할 수 없으므로, 별도의 정적 필드인 stringToEnum 맵을 사용하고 있다. 열거 타입의 생성자가 실행되는 시점에는 정적 필드들이 초기화되기 전이므로 자기 자신을 추가하지 못하게 하는 제약이 필요하다. 
-> Item 24 참고해보세요. Enum 타입이 싱글턴과 비슷하다는 것을 기억하세요.

**Comment by psychology50** [comment]
enum type 상수는 생성자에서 자신의 인스턴스를 맵에 추가할 수 없다.

enum type의 정적 필드 중 생성자에서 접근할 수 있는 것은 상수 변수 뿐이다. (Item 24)

enum type 생성자가 실행되는 시점에는 정적 필드들이 초기화 되기 전이라 자기 자신을 추가하지 못하도록 제약이 꼭 필요하다.

 

이 제약의 특수한 예로, enum type 생성자에서 같은 enum type의 다른 상수에도 접근할 수 없다.

**Comment by joyerimi** [comment]
enum 타입, 생성자, 초기화 시점에 대해 정리하겠습니다.

1. Enum 타입 상수는 생성자에서 자신의 인스턴스를 맵에 추가할 수 없습니다.

: Enum 타입의 생성자가 실행되는 시점에는 enum 상수가 완전히 생성되지 않은 상태입니다. 따라서 맵과 같은 다른 데이터 구조에 추가할 수 없습니다. 

2. Enum 타입의 정적 필드 중에서 생성자에서 접근할 수 있는 것은 상수 변수 뿐입니다.

: enum 타입의 정적 필드들은 enum 상수들이 모두 생성된 이후에 초기화됩니다. enum 타입의 생성자에서 이러한 정적 필드에 접근하는 것은 불가능합니다. 반면 상수 변수는 생성자에서 접근이 가능합니다.

"Enum 타입 생성자가 실행되는 시점에는 정적 필드들이 초기화되기 전이라 자기 자신을 추가하지 못하도록 제약이 필요하다", "Enum 타입 생성자에서 같은 enum 타이븨 다른 상수에도 접근할 수 없다"도 결국에는 위와 같은 이유입니다.
