### ISSUE TITLE
아이템 39. 명명 패턴보다 애너테이션을 사용하라

### ISSUE THREAD

**Issue by AHNDOIL** [psychology50/effective-java-study#25]

**Comment by psychology50** [comment]
반복 가능 애너테이션 @Repeatable에서 컨테이너 애너테이션이 필요한 이유가 무엇이라 생각하나요?
isAnnotationPresent()가 둘을 구분해서 문제가 생긴다고 하는데, 하나만 달았을 때와 여러 개를 달았을 때 반환 타입이 어떻게 다르길래 구분해서 판단해야 하나요?

**Comment by AHNDOIL** [comment]
컨테이너 애너테이션은 반복 가능 애너테이션을 여러 개 달았을 때와 하나만 달았을 때를 구분하기 위해 사용합니다.
컨테이너 애너테이션은 반복 가능한 애너테이션을 감싸는 역할을 수행하며, 반복 가능한 애너테이션의 배열로서 동작합니다. 예를 들어, @Reapeatable 애너테이션 A를 컨테이너 애너테이션 B가 감싸고 있을 때, B를 통해 A의 인스턴스들을 구분할 수 있습니다.

반복 가능한 애너테이션을 단일로 사용한 경우와 컨테이너 애너테이션을 통해 여러 개를 사용한 경우의 isAnnotationPresent() 메서드의 반환 타입은 다릅니다. 반복 가능한 애너테이션을 단일로 사용한 경우에는 해당 애너테이션 타입의 인스턴스를 반환하지만, 컨테이너 애너테이션을 통해 여러 개를 사용한 경우에는 컨테이너 애너테이션 타입의 배열을 반환합니다.
따라서 애너테이션이 달려 있는 수와 상관 없이 모두 검사하려면 둘을 따로따로 확인해야 합니다.
