### ISSUE TITLE
아이템 41. 정의하려는 것이 타입이라면 마커 인터페이스를 사용하라

### ISSUE THREAD

**Issue by AHNDOIL** [psychology50/effective-java-study#27]

**Comment by psychology50** [comment]
Serializable을 구현한 클래스는 ObjectOutputStream.writeObject()를 사용할 수 있는 이유는 무엇인가요? Serializerable은 아무 것도 구현하지 않는 인터페이스지 않나요?
예시가 궁금합니다.

**Comment by AHNDOIL** [comment]
예를 들어, 마커 인터페이스는 ObjectOutputStream.wirteObject() 인수로 Serializerable을 받도록 합니다. 따라서 Serializerable을 구현하지 않은 클래스는 이를 사용할 수 없습니다. 

```java

public class Main {
    static void newWriteObject(Serializable object, String path) {
        File file = new File(path);

        try (ObjectOutputStream oops = new ObjectOutputStream(new FileOutputStream(file))) {
            oops.writeObject(object);
        } catch (IOException e) {
            System.out.println("Runtime Error");
        }
    }
}

```

하지만 실제로 ObjectOutputStream.writeObject 메서드는  Serializable이 아닌 Object로 구현되어 있긴 합니다.
