### ISSUE TITLE
아이템 43. 람다보다는 메서드 참조를 사용하라

### ISSUE THREAD

**Issue by psychology50** [psychology50/effective-java-study#29]

**Comment by AHNDOIL** [comment]
메서드 참조 유형에는 한정적 인스턴스 메서드 참조와 비한정적 인스턴스 메서드 참조가 있는데, 둘은 어떻게 구분하고 왜 구분하여 사용되나요?

**Comment by psychology50** [comment]
[Method References](https://docs.oracle.com/javase/tutorial/java/javaOO/methodreferences.html)  
`한정적 참조는 근본적으로 정적 참조와 비슷하고, 비한정적 참조는 함수 객체를 적용하는 시점에 수신 객체를 알려준다`

우선 a, b 두개의 매개변수에 대해 메소드 호출 유형은 크게 4가지로 나눌 수 있습니다.
1. `Class::staticMethod`
    - `(a, b) -> Class.staticMethod(a, b)`
2. `object::method`
    - `(a, b) -> object.method(a, b)`
3. `Class::method`
    - `(a, b) -> a.method(b)`
4. `Class:new`
    - `(a, b) -> new Class(a, b)` 
  
(2)번의 경우에는 object라는 인스턴스가 어떠한 기능을 할 것이라 특정 짓고 있습니다.  
책에 나온 예시를 보면 이렇게 말하고 있어요.  
`Instant.now()::isAfter`는 람다식으로 `Instant then = Instant.now(); t -> the.isAfter(t)`와 같다.  
즉, Instant.now()가 특정 object를 반환하고, 해당 object의 method인 isAfter를 호출하고 있으므로 수신 객체를 특정하고 있다고 볼 수 있습니다.
  
반면 (3)의 경우에는 메서드를 호출하는 수신 객체마저 함수 객체를 적용한 시점에야 알 수 있습니다.  
호출자가 있어야 하므로 수신 객체 전달용 매개변수가 매개변수 목록의 첫 번째로 추가되고, 그 뒤아 참조 되는 메서드 선언에 정의된 매개변수들이 뒤따른다고 책에서 설명하고 있습니다.
