### ISSUE TITLE
아이템 45. 스트림은 주의해서 사용하라

### ISSUE THREAD

**Issue by AHNDOIL** [psychology50/effective-java-study#31]

**Comment by psychology50** [comment]
스트림에서는 final 변수만 읽을 수 있는 이유..지역 변수 수정이 왜 불가능한가요?

**Comment by joyerimi** [comment]
람다가 왜 사용되나요?

**Comment by AHNDOIL** [comment]
> 스트림에서는 final 변수만 읽을 수 있는 이유..지역 변수 수정이 왜 불가능한가요?

final 변수는 변수 값을 한 번 설정하면 그 이후로는 수정할 수 없기 때문에, 스트림 연산을 수행하는 동안 변수 값이 변하지 않음이 보장됩니다. 따라서 이러한 불변성을 가지는 final 변수들을 사용하면 스트림 연산이 안전하게 수행되고, 다중 스레드 환경에서도 예측 가능한 결과를 얻을 수 있습니다.

지역 변수는 메서드 내에서만 사용되는 변수로, 스트림 연산 중에 지역 변수가 수정되면 다른 부분에서 예상치 못한 동작을 초래할 수 있습니다. 함수형 프로그래밍에서는 동일한 입력에 대해 항상 동일한 결과가 나와야 하므로, 스트림에서 지역 변수의 수정을 허용하지 않습니다.

**Comment by AHNDOIL** [comment]
> 람다가 왜 사용되나요?

람다를 사용하면 코드가 간결해지고 가독성이 향상되며, 함수형 프로그래밍을 지원하므로 유연하고 강력한 프로그래밍 스타일을 적용할 수 있습니다.
