### ISSUE TITLE
아이템 55. 옵셔널 반환은 신중히 하라

### ISSUE THREAD

**Issue by AHNDOIL** [psychology50/effective-java-study#41]

**Comment by psychology50** [comment]
Intance field로 Optional을 지정하면, 필수 필드를 갖는 클래스와, 이를 확장해 선택적 필드를 추가한 하위 클래스를 따로 만들어야 함을 암시한다. ('나쁜 냄새'의 예시가 궁금합니다.)

**Comment by AHNDOIL** [comment]
```java
class Person {
    private String name;
    private Optional<Integer> age;

    public Person(String name, Optional<Integer> age) {
        this.name = name;
        this.age = age;
    }

   //Getter, Setter..
}
```

위 클래스에서 age는 Optional<Integer>로 선언되어 선택적 필드로 간주됩니다. Person 클래스를 확장한 하위 클래스는 age 필드를 선택적으로 가지는 하위 클래스와, 필수적으로 가지는 하위 클래스를 따로 만들어야할 수도 있습니다.

이 때문에 이러한 코드에서는 소위 '나쁜 냄새'를 풍긴다고 합니다.

추가적으로,
1. 코드의 가독성이 떨어지고, 디버깅이 어려워질 수 있습니다.
2. 하위 클래스에 대한 유지보수가 어려워질 수 있습니다.
3. 새로운 하위 클래스가 추가될 때마다 해당 클래스가 어떤 필드를 선택적으로 사용해야 하는지 파악하는 것이 어려울 수 있습니다.

이러한 이유도 존재합니다.
